### ISSUE TITLE
Pisanje izvestaja

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG143-doodle-jump#3]
Izvestaje je neophodno pisati tokom rada na projektu i to na wiki stranici vaseg repozitorijuma, tako odradite to za dosadasnji rad i dodajte nove izvestaje tamo. Informacije o tome sta izvestaji treba da sadrze mozete naci na mom sajtu (http://www.matf.bg.ac.rs/p/rastko-djordjevic/cas/2715/izrada-projekata/).

**Comment by duhizjame** [comment]
Dodati izvestaji u wiki.
