### ISSUE TITLE
Unapredjivanje platformi

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG143-doodle-jump#4]
Dodati razlicite osobine za razlicite podloge. Na primer plava moze biti led po kojoj se igrac kliza (ima manje trenje), neka druga moze imati veci/manji odskok, neka moze imati osobinu da se igrac zalepi za nju (nema trenja), neka moze nestati nakon sto igrac skoci sa nje, itd.

**Comment by duhizjame** [comment]
Dodate razlicite osobine preprekama.
